/** this class is autogenerated from AVE */
class InfiniteLoop extends HTMLElement {
  /** called when DOM element is rendered */
  connectedCallback() {
    this.render();
    this.attach();
  }
  /** called when DOM element is disposed */
  disconnectedCallback() {
    this.detach();
  }
  /** called when 'infinite-loop-update' event is called */
  updateCallback(event) {
    /** use event.details to get data from event */
  }
  /** called when 'infinite-loop' is created */
  attach() {
    window.addEventListener('infinite-loop-update', this.updateCallback);
    this.dispatchEvent(new CustomEvent('infinite-loop-initialized', {
      bubbles: true,
    }));
  }
  /** called when 'infinite-loop' is destroyed */
  detach() {
    window.removeEventListener('infinite-loop-update', this.updateCallback);
    this.dispatchEvent(new CustomEvent('infinite-loop-disposed', {
      bubbles: true,
    }));
  }
  /** render method - put here HTML */
  render(data){
    window.requestAnimationFrame(() => {
      this.innerHTML = '<iframe width="100%" height="100%" src="http://localhost:4300/"></iframe>';
    });
  }
}
window.customElements.define('infinite-loop', InfiniteLoop);